import keyMirror from 'keymirror';

export default keyMirror({
  SET_SELECTED_INTERNAL_ACCOUNT: null,
  GET_SELECTED_INTERNAL_ACCOUNT: null,

  GET_INTERNAL_ACCOUNTS: null,
  GET_INTERNAL_ACCOUNTS_SUCCESS: null,
  GET_INTERNAL_ACCOUNTS_FAILURE: null,

  GET_EXTERNAL_ACCOUNTS: null,
  GET_EXTERNAL_ACCOUNTS_SUCCESS: null,
  GET_EXTERNAL_ACCOUNTS_FAILURE: null
});
